from __future__ import annotations

SECTION_IDS = {
    "front_left_top": 1,
    "front_left_ring": 2,
    "front_left_rib": 3,
    "front_left_abs": 4,
    "front_left_belt": 5,
    "back_left_belt": 6,
    "back_left_vertebra": 7,
    "back_left_rib": 8,
    "back_left_top": 9,
    "left_upper_arm": 10,
    "left_forearm": 11,
    "front_right_top": 12,
    "front_right_rib": 13,
    "front_right_abs": 14,
    "front_right_belt": 15,
    "back_right_belt": 16,
    "back_right_vertebra": 17,
    "back_right_rib": 18,
    "back_right_top": 19,
    "right_upper_arm": 20,
    "right_forearm": 21,
    "left_thigh_front": 22,
    "left_shin_f_in": 23,
    "left_shin_f_out": 24,
    "left_thigh_back": 25,
    "left_shin_b_in": 26,
    "left_shin_b_out": 27,
    "right_thigh_front": 28,
    "right_shin_f_in": 29,
    "right_shin_f_out": 30,
    "right_thigh_back": 31,
    "right_shin_b_in": 32,
    "right_shin_b_out": 33,
}

GROUP_IDS = {
    "all": 1,
    "front_all": 2,
    "back_all": 3,
    "left_all": 4,
    "right_all": 5,
    "torso_all": 6,
    "arms_all": 7,
    "left_arm_all": 8,
    "right_arm_all": 9,
    "ring": 10,
    "belt_all": 11,
    "spine": 12,
    "legs_all": 13,
    "left_leg_all": 14,
    "right_leg_all": 15,
    "left_thigh_all": 16,
    "left_shin_all": 17,
    "right_thigh_all": 18,
    "right_shin_all": 19,
}

ROLE_NAMES = ("A", "B", "C")

GROUP_SECTIONS = {
    "all": tuple(SECTION_IDS.keys()),
    "front_all": (
        "front_left_top",
        "front_left_ring",
        "front_left_rib",
        "front_left_abs",
        "front_left_belt",
        "front_right_top",
        "front_right_rib",
        "front_right_abs",
        "front_right_belt",
    ),
    "back_all": (
        "back_left_belt",
        "back_left_vertebra",
        "back_left_rib",
        "back_left_top",
        "back_right_belt",
        "back_right_vertebra",
        "back_right_rib",
        "back_right_top",
    ),
    "left_all": (
        "front_left_top",
        "front_left_ring",
        "front_left_rib",
        "front_left_abs",
        "front_left_belt",
        "back_left_belt",
        "back_left_vertebra",
        "back_left_rib",
        "back_left_top",
        "left_upper_arm",
        "left_forearm",
        "left_thigh_front",
        "left_shin_f_in",
        "left_shin_f_out",
        "left_thigh_back",
        "left_shin_b_in",
        "left_shin_b_out",
    ),
    "right_all": (
        "front_right_top",
        "front_right_rib",
        "front_right_abs",
        "front_right_belt",
        "back_right_belt",
        "back_right_vertebra",
        "back_right_rib",
        "back_right_top",
        "right_upper_arm",
        "right_forearm",
        "right_thigh_front",
        "right_shin_f_in",
        "right_shin_f_out",
        "right_thigh_back",
        "right_shin_b_in",
        "right_shin_b_out",
    ),
    "torso_all": (
        "front_left_top",
        "front_left_ring",
        "front_left_rib",
        "front_left_abs",
        "front_left_belt",
        "back_left_belt",
        "back_left_vertebra",
        "back_left_rib",
        "back_left_top",
        "front_right_top",
        "front_right_rib",
        "front_right_abs",
        "front_right_belt",
        "back_right_belt",
        "back_right_vertebra",
        "back_right_rib",
        "back_right_top",
    ),
    "arms_all": (
        "left_upper_arm",
        "left_forearm",
        "right_upper_arm",
        "right_forearm",
    ),
    "left_arm_all": (
        "left_upper_arm",
        "left_forearm",
    ),
    "right_arm_all": (
        "right_upper_arm",
        "right_forearm",
    ),
    "ring": ("front_left_ring",),
    "belt_all": (
        "front_left_belt",
        "back_left_belt",
        "front_right_belt",
        "back_right_belt",
    ),
    "spine": (
        "back_left_vertebra",
        "back_right_vertebra",
    ),
    "legs_all": (
        "left_thigh_front",
        "left_shin_f_in",
        "left_shin_f_out",
        "left_thigh_back",
        "left_shin_b_in",
        "left_shin_b_out",
        "right_thigh_front",
        "right_shin_f_in",
        "right_shin_f_out",
        "right_thigh_back",
        "right_shin_b_in",
        "right_shin_b_out",
    ),
    "left_leg_all": (
        "left_thigh_front",
        "left_shin_f_in",
        "left_shin_f_out",
        "left_thigh_back",
        "left_shin_b_in",
        "left_shin_b_out",
    ),
    "right_leg_all": (
        "right_thigh_front",
        "right_shin_f_in",
        "right_shin_f_out",
        "right_thigh_back",
        "right_shin_b_in",
        "right_shin_b_out",
    ),
    "left_thigh_all": (
        "left_thigh_front",
        "left_thigh_back",
    ),
    "left_shin_all": (
        "left_shin_f_in",
        "left_shin_f_out",
        "left_shin_b_in",
        "left_shin_b_out",
    ),
    "right_thigh_all": (
        "right_thigh_front",
        "right_thigh_back",
    ),
    "right_shin_all": (
        "right_shin_f_in",
        "right_shin_f_out",
        "right_shin_b_in",
        "right_shin_b_out",
    ),
}


def section_id(name: str) -> int:
    return SECTION_IDS[name]


def group_id(name: str) -> int:
    return GROUP_IDS[name]


def group_sections(name: str) -> tuple[str, ...]:
    return GROUP_SECTIONS[name]
